var tableauQuestion = [
    {   question : "Vous êtes en train de conduire à 90 kmh, vous vous approchez d'une zone résidentielle, que faites-vous ?",
        propositionA : "J'accélére !",
        propositionB : "Je peux accélérer tant qu'il n'y a pas d'autres voitures.",
        propositionC : "Je ralentis.",
        propositionD : "Je peux maintenir ma vitesse.",
        reponse : "C"},
		
    {   question : "Le feu est vert, vous vous apprètez à tourner à gauche, vous apercevez un pièton dans la direction du passage clouté. Qui a le droit de passage ?",
        propositionA : "Le pièton, parce qu'il a le droit de traverser la route sur n'importe quel feu.",
        propositionB : "Mon vehicule car le feu est vert.",
        propositionC : "Le pièton, parce qu'il traverse au feu vert.",
        propositionD : "Mon véhicule, car j'ai tout le temps la priorité.",
        reponse : "B"},
		
    {   question : "la vitesse maximale dans une zone résidentielle est de ____ .",
        propositionA : "50 kmh",
        propositionB : "60 kmh",
        propositionC : "65 kmh",
        propositionD : "70 kmh",
        reponse : "A"},
	
	{   question : "Vous roulez à 90 Kmh, un chat déboule soudainement devant vous, vous remarquez qu'il y a une voiture qui arrive derrière, que faites-vous ?",
        propositionA : "Je klaxone et j'évite l'animal en débordant sur l'autre voie.",
        propositionB : "Je freine.",
        propositionC : "Tant pis, je roule sur l'animal je ne risque pas l'accident.",
        propositionD : "Je ralenti.",
        reponse : "C"},
		
	{   question : "Le feu est rouge mais, je suis sur la voie de droite afin de m'y engager pour tourner. Que devez-vous faire ?",
        propositionA : "J'attend que le feu passe au vert et je tourne à droite.",
        propositionB : "Je peux directement tourner à droite en indiquant avec mon clignotant.",
        propositionC : "je ralenti, mets mon clignotant et tourne à droite.",
        propositionD : "J'accélère, je tourne à droite.",
        reponse : "C"},
		
	{   question : "Un véhicule d'urgence gyrophares et sirènes allumer arrive derrière vous, que faites-vous ?",
        propositionA : "Je suis pressé(e), j'accélère.",
        propositionB : "J'ai de la place sur une autre voies.",
        propositionC : "Je me sert sur le coté et attend son passage.",
        propositionD : "Je me sert sur le coté et en profite pour le suivre et passer les feux.",
        reponse : "c"},
	
	{   question : "Un véhicule de police vous fait signe, gyrophare allumer et vous klaxone que faites-vous ?",
        propositionA : "Il veux surement me controller, je ralentit, indique mon intention de me ranger sur le coté et j'attends mon controle.",
        propositionB : "Mon véhicule est carrément plus rapide, j'ai pas le temps pour un controle.",
        propositionC : "je continue de rouler à la même allure.",
        propositionD : "Je fait signe au policier de passer.",
        reponse : "A"},
		
	{   question : "Laquelle de ces situations sont permise quand vous souhaitez depasser un autre vehicule ?",
        propositionA : "J'accélère et le double.",
        propositionB : "Il y a un trottoir, je m'engage dessus pour le dépasser.",
        propositionC : "Je peux doubler par la gauche, il n'y a aucun véhicule devant, j'indique mon intention avec mon clignotant.",
        propositionD : "Je klaxone pour le faire accélérer.",
        reponse : "C"},
		
	{   question : "Vous conduisez sur la freeway, la limite est de 140Kmh. La plupart des gens autour de vous roule à 150 kmh, Je dois rouler au maximum à :",
        propositionA : "110 kmh",
        propositionB : "150 kmh",
        propositionC : "80 kmh",
        propositionD : "140 kmh",
        reponse : "D"},
		
	{   question : "Le feu passe au orange que devez-vous faire ?",
        propositionA : "Ralentir et je passe.",
        propositionB : "Je m'arrête au feu.",
        propositionC : "Je ralentis et m'arrête au feu.",
        propositionD : "J'accélére et je passe pour ne pas avoir de feu rouge.",
        reponse : "C"},
]
